artifact_uri: file:///home/aura-alexis/github/ecg_qc_training/mlruns/0/ef5fc4b104a74ecba054d5f3dd33084c/artifacts
end_time: 1627897525576
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: ef5fc4b104a74ecba054d5f3dd33084c
run_uuid: ef5fc4b104a74ecba054d5f3dd33084c
source_name: ''
source_type: 4
source_version: ''
start_time: 1627897507438
status: 3
tags: []
user_id: aura-alexis
